name: loftr
channels:
  # - https://dx-mirrors.sensetime.com/anaconda/cloud/pytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.2
  - pytorch=1.8.1
  - pip
  - pip:
      - -r requirements.txt
